### ISSUE TITLE
Cannot set election time to now

### ISSUE THREAD

**Issue by apuignav** [gdujany/Condorcet#18]
When I try to set election time to now using the button, I get the following error

```
127.0.0.1 - - [21/Apr/2015 13:20:48] "POST /setToNow/START_ELECTION HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/albert/Arxiu/Fisica/LHCb/Projectes/PCElection/Condorcet/Condorcet/__init__.py", line 87, in decorated_function
    return f(*args, **kwargs)
  File "/Users/albert/Arxiu/Fisica/LHCb/Projectes/PCElection/Condorcet/Condorcet/__init__.py", line 267, in setToNow
    time.localtime())
  File "/Users/albert/Arxiu/Fisica/LHCb/Projectes/PCElection/Condorcet/Condorcet/updateConfig.py", line 101, in setConfig
    setattr(Config.query.filter_by(KEY=KEY).first(), field, value)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2370, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2231, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: config u'SELECT config."KEY" AS "config_KEY", config."TITLE" AS "config_TITLE", config."OPTIONS" AS "config_OPTIONS", config."CONTACT" AS "config_CONTACT", config."DATE_FORMAT" AS "config_DATE_FORMAT", config."START_ELECTION" AS "config_START_ELECTION", config."CLOSE_ELECTION" AS "config_CLOSE_ELECTION", config."VIEW_RESULTS" AS "config_VIEW_RESULTS", config."AUTHORS_LIST" AS "config_AUTHORS_LIST" \nFROM config \nWHERE config."KEY" = ?\n LIMIT ? OFFSET ?' ('default', 1, 0)
```

I have reset de DB before, but it doesn't seem to help. Am I missing something?

**Comment by gdujany** [comment]
You probably need to generate the config database 
Condorcet/updateConfig.py --reset
should do the job, let me know if it doesn't work that I'll investigate further

**Comment by apuignav** [comment]
It works. This has become more complicated. I'll work on the interface now.

**Comment by gdujany** [comment]
Yes, I am sorry. I tried to keep the config db separate from the voters' one. In any case I also updated setup.sh so a priory if you start form scratch and run it, everythong should work out of the box
